export const FETCH_STORE_LIST = 'FETCH_STORE_LIST';
export const FETCH_STORE_LIST_BY_TAG = 'FETCH_STORE_LIST_BY_TAG';
export const FETCH_NEARBY_STORE_LIST = 'FETCH_NEARBY_STORE_LIST'; // 離我最近
export const FETCH_RECOMMEND_STORE_LIST = 'FETCH_RECOMMEND_STORE_LIST'; // 猜你想吃
export const FETCH_HOT_STORE_LIST = 'FETCH_HOT_STORE_LIST'; // 熱門推薦
export const FETCH_SLIDES_DATA = 'FETCH_SLIDES_DATA';
